//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almg.MobileSigner.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Almg.MobileSigner.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        public static string ACTIONS {
            get {
                return ResourceManager.GetString("ACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplicativo do SILEGIS está sendo configurado....
        /// </summary>
        public static string APP_IS_BEING_CONFIGURED {
            get {
                return ResourceManager.GetString("APP_IS_BEING_CONFIGURED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silegis.
        /// </summary>
        public static string APP_TITLE {
            get {
                return ResourceManager.GetString("APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivar.
        /// </summary>
        public static string ARCHIVE {
            get {
                return ResourceManager.GetString("ARCHIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivando.
        /// </summary>
        public static string ARCHIVING {
            get {
                return ResourceManager.GetString("ARCHIVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha ao obter a senha do certificado..
        /// </summary>
        public static string ASK_PASSWORD_ERROR {
            get {
                return ResourceManager.GetString("ASK_PASSWORD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O dispositivo não possui nenhum aplicativo capaz de abrir o formato do arquivo..
        /// </summary>
        public static string ATTACHMENT_FILE_TYPE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("ATTACHMENT_FILE_TYPE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexos.
        /// </summary>
        public static string ATTACHMENTS {
            get {
                return ResourceManager.GetString("ATTACHMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autores.
        /// </summary>
        public static string AUTHORS {
            get {
                return ResourceManager.GetString("AUTHORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar requisição.
        /// </summary>
        public static string CANCEL_REQUEST {
            get {
                return ResourceManager.GetString("CANCEL_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha ao cancelar a solicitação..
        /// </summary>
        public static string CANCEL_REQUEST_FAILED {
            get {
                return ResourceManager.GetString("CANCEL_REQUEST_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A solicitação será removida permanentente da caixa de entrada. Deseja continuar?.
        /// </summary>
        public static string CANCEL_REQUEST_QUESTION {
            get {
                return ResourceManager.GetString("CANCEL_REQUEST_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelando solicitação....
        /// </summary>
        public static string CANCELING_REQUEST {
            get {
                return ResourceManager.GetString("CANCELING_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um novo certificado digital está disponível. Deseja realizar a instalação agora?.
        /// </summary>
        public static string CERT_UPDATE_AVAILABLE {
            get {
                return ResourceManager.GetString("CERT_UPDATE_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro na atualização do certificado digital..
        /// </summary>
        public static string CERT_UPDATE_FAILED {
            get {
                return ResourceManager.GetString("CERT_UPDATE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O certificado digital já está na versão mais recente. A atualização não foi realizada..
        /// </summary>
        public static string CERT_UPDATE_NOT_REQUIRED {
            get {
                return ResourceManager.GetString("CERT_UPDATE_NOT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O certificado digital cadastrado no aplicativo está expirado e não pode ser utilizado para realizar novas assinaturas..
        /// </summary>
        public static string CERTIFICATE_EXPIRED {
            get {
                return ResourceManager.GetString("CERTIFICATE_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha ao obter as configurações.
        /// </summary>
        public static string CERTIFICATE_LOAD_ERROR {
            get {
                return ResourceManager.GetString("CERTIFICATE_LOAD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O certificado digital foi carregado com sucesso..
        /// </summary>
        public static string CERTIFICATE_LOAD_SUCCESS {
            get {
                return ResourceManager.GetString("CERTIFICATE_LOAD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao gravar o certificado no armazenamento local.
        /// </summary>
        public static string CERTIFICATE_SAVE_ERROR {
            get {
                return ResourceManager.GetString("CERTIFICATE_SAVE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        public static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        public static string CONFIGURATION_TITLE {
            get {
                return ResourceManager.GetString("CONFIGURATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horário de elaboração.
        /// </summary>
        public static string CREATION_TIME {
            get {
                return ResourceManager.GetString("CREATION_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criador.
        /// </summary>
        public static string CREATOR {
            get {
                return ResourceManager.GetString("CREATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recusar requisição.
        /// </summary>
        public static string DENY_REQUEST {
            get {
                return ResourceManager.GetString("DENY_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha ao recusar a assinatura..
        /// </summary>
        public static string DENY_REQUEST_FAILED {
            get {
                return ResourceManager.GetString("DENY_REQUEST_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ao recusar a solicitação de assinatura ela será removida permanentemente da caixa de entrada e o SILEGIS irá informar o gabinete solicitante da recusa. Deseja continuar?.
        /// </summary>
        public static string DENY_REQUEST_QUESTION {
            get {
                return ResourceManager.GetString("DENY_REQUEST_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recusando solicitação....
        /// </summary>
        public static string DENYING_REQUEST {
            get {
                return ResourceManager.GetString("DENYING_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro durante a realização da assinatura digital. O documento não foi assinado..
        /// </summary>
        public static string DIGITAL_SIGNATURE_FAILED {
            get {
                return ResourceManager.GetString("DIGITAL_SIGNATURE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro imprevisto durante a realização da assinatura digital. O documento não foi assinado..
        /// </summary>
        public static string DIGITAL_SIGNATURE_FAILED_UNKNOW_REASON {
            get {
                return ResourceManager.GetString("DIGITAL_SIGNATURE_FAILED_UNKNOW_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assinatura realizada com sucesso..
        /// </summary>
        public static string DIGITAL_SIGNATURE_SUCCESS {
            get {
                return ResourceManager.GetString("DIGITAL_SIGNATURE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha ao carregar o documento..
        /// </summary>
        public static string DOCUMENT_LOADING_FAILED {
            get {
                return ResourceManager.GetString("DOCUMENT_LOADING_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações.
        /// </summary>
        public static string DOCUMENT_METADATA {
            get {
                return ResourceManager.GetString("DOCUMENT_METADATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download em andamento....
        /// </summary>
        public static string DOWNLOADING {
            get {
                return ResourceManager.GetString("DOWNLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível obter a lista de documentos.
        /// </summary>
        public static string ERROR_UNABLE_TO_REACH_REQUEST_LIST_API {
            get {
                return ResourceManager.GetString("ERROR_UNABLE_TO_REACH_REQUEST_LIST_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string EXCEPTION_CODE {
            get {
                return ResourceManager.GetString("EXCEPTION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível carregar as requisições de assinatura..
        /// </summary>
        public static string FAILED_LOADING_SIGNATURE_REQUESTS {
            get {
                return ResourceManager.GetString("FAILED_LOADING_SIGNATURE_REQUESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha ao abrir o arquivo PDF.
        /// </summary>
        public static string FAILED_TO_LOAD_PDF {
            get {
                return ResourceManager.GetString("FAILED_TO_LOAD_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível abrir o anexo.
        /// </summary>
        public static string FAILED_TO_OPEN_ATTACHMENT {
            get {
                return ResourceManager.GetString("FAILED_TO_OPEN_ATTACHMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutas assinadas.
        /// </summary>
        public static string FINISHED_REQUESTS {
            get {
                return ResourceManager.GetString("FINISHED_REQUESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocultar arquivadas.
        /// </summary>
        public static string HIDE_ARCHIVED {
            get {
                return ResourceManager.GetString("HIDE_ARCHIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorar assinatura.
        /// </summary>
        public static string IGNORAR_ASSINATURA {
            get {
                return ResourceManager.GetString("IGNORAR_ASSINATURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha ao ignorar a assinatura..
        /// </summary>
        public static string IGNORAR_ASSINATURA_FAILED {
            get {
                return ResourceManager.GetString("IGNORAR_ASSINATURA_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorando assinatura....
        /// </summary>
        public static string IGNORAR_ASSINATURA_PROGRESS {
            get {
                return ResourceManager.GetString("IGNORAR_ASSINATURA_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja ignorar a assinatura?.
        /// </summary>
        public static string IGNORAR_ASSINATURA_QUESTION {
            get {
                return ResourceManager.GetString("IGNORAR_ASSINATURA_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorar.
        /// </summary>
        public static string IGNORE {
            get {
                return ResourceManager.GetString("IGNORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorar requisição.
        /// </summary>
        public static string IGNORE_REQUEST {
            get {
                return ResourceManager.GetString("IGNORE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao ignorar a solicitação..
        /// </summary>
        public static string IGNORE_REQUEST_FAILED {
            get {
                return ResourceManager.GetString("IGNORE_REQUEST_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ao ignorar a solicitação de assinatura ela será removida permanentemente da caixa de entrada e o gabinete solicitante não será informado. Deseja continuar?.
        /// </summary>
        public static string IGNORE_REQUEST_QUESTION {
            get {
                return ResourceManager.GetString("IGNORE_REQUEST_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorando solicitação....
        /// </summary>
        public static string IGNORING_REQUEST {
            get {
                return ResourceManager.GetString("IGNORING_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite a senha do certificado digital:.
        /// </summary>
        public static string INPUT_PKCS12_PASSWORD {
            get {
                return ResourceManager.GetString("INPUT_PKCS12_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O dispositivo está offline. Verifique a conexão com a internet e tente novamente..
        /// </summary>
        public static string INTERNET_UNAVAILABLE {
            get {
                return ResourceManager.GetString("INTERNET_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando documento....
        /// </summary>
        public static string LOADING_DOCUMENT {
            get {
                return ResourceManager.GetString("LOADING_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando informações do documento....
        /// </summary>
        public static string LOADING_DOCUMENT_INFO {
            get {
                return ResourceManager.GetString("LOADING_DOCUMENT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando PDF....
        /// </summary>
        public static string LOADING_PDF {
            get {
                return ResourceManager.GetString("LOADING_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizando login....
        /// </summary>
        public static string LOGGING_IN {
            get {
                return ResourceManager.GetString("LOGGING_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar o login..
        /// </summary>
        public static string LOGIN_ERROR {
            get {
                return ResourceManager.GetString("LOGIN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LOGIN_TITLE {
            get {
                return ResourceManager.GetString("LOGIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja realizar o logout da aplicação? Caso afirmativo, será necessário habilitar o dispositivo novamente para acessar o Silegis..
        /// </summary>
        public static string LOGOUT_CONFIRM {
            get {
                return ResourceManager.GetString("LOGOUT_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meu Gabinete.
        /// </summary>
        public static string MY_DOCUMENTS {
            get {
                return ResourceManager.GetString("MY_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma requisição.
        /// </summary>
        public static string NO_REQUESTS {
            get {
                return ResourceManager.GetString("NO_REQUESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outros.
        /// </summary>
        public static string OTHER_DOCUMENTS {
            get {
                return ResourceManager.GetString("OTHER_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocolar documento.
        /// </summary>
        public static string PROTOCOLAR {
            get {
                return ResourceManager.GetString("PROTOCOLAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao protocolar o documento..
        /// </summary>
        public static string PROTOCOLAR_FAILED {
            get {
                return ResourceManager.GetString("PROTOCOLAR_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguarde, protocolando o documento....
        /// </summary>
        public static string PROTOCOLAR_PROGRESS {
            get {
                return ResourceManager.GetString("PROTOCOLAR_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja protocolar o documento?.
        /// </summary>
        public static string PROTOCOLAR_QUESTION {
            get {
                return ResourceManager.GetString("PROTOCOLAR_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recusar assinatura.
        /// </summary>
        public static string RECUSAR_ASSINATURA {
            get {
                return ResourceManager.GetString("RECUSAR_ASSINATURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha ao recusar a assinatura..
        /// </summary>
        public static string RECUSAR_ASSINATURA_FAILED {
            get {
                return ResourceManager.GetString("RECUSAR_ASSINATURA_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recusando a assinatura....
        /// </summary>
        public static string RECUSAR_ASSINATURA_PROGRESS {
            get {
                return ResourceManager.GetString("RECUSAR_ASSINATURA_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja recusar a assinatura?.
        /// </summary>
        public static string RECUSAR_ASSINATURA_QUESTION {
            get {
                return ResourceManager.GetString("RECUSAR_ASSINATURA_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover assinatura.
        /// </summary>
        public static string REMOVER_ASSINATURA {
            get {
                return ResourceManager.GetString("REMOVER_ASSINATURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao remover a assinatura..
        /// </summary>
        public static string REMOVER_ASSINATURA_FAILED {
            get {
                return ResourceManager.GetString("REMOVER_ASSINATURA_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removendo assinatura....
        /// </summary>
        public static string REMOVER_ASSINATURA_PROGRESS {
            get {
                return ResourceManager.GetString("REMOVER_ASSINATURA_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja remover a assinatura?.
        /// </summary>
        public static string REMOVER_ASSINATURA_QUESTION {
            get {
                return ResourceManager.GetString("REMOVER_ASSINATURA_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encerrada.
        /// </summary>
        public static string REQUEST_STATUS_FINISHED {
            get {
                return ResourceManager.GetString("REQUEST_STATUS_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atendida.
        /// </summary>
        public static string REQUEST_STATUS_SIGNED {
            get {
                return ResourceManager.GetString("REQUEST_STATUS_SIGNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exibir arquivadas.
        /// </summary>
        public static string SHOW_ARCHIVED {
            get {
                return ResourceManager.GetString("SHOW_ARCHIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assinar Documento.
        /// </summary>
        public static string SIGN_DOCUMENT {
            get {
                return ResourceManager.GetString("SIGN_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assinar Documentos.
        /// </summary>
        public static string SIGN_DOCUMENTS {
            get {
                return ResourceManager.GetString("SIGN_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A assinatura digital foi cancelada..
        /// </summary>
        public static string SIGNATURE_CANCELLED {
            get {
                return ResourceManager.GetString("SIGNATURE_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisições.
        /// </summary>
        public static string SIGNATURE_REQUESTS {
            get {
                return ResourceManager.GetString("SIGNATURE_REQUESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assinado.
        /// </summary>
        public static string SIGNED {
            get {
                return ResourceManager.GetString("SIGNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assinando....
        /// </summary>
        public static string SIGNING {
            get {
                return ResourceManager.GetString("SIGNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chave.
        /// </summary>
        public static string TOKEN {
            get {
                return ResourceManager.GetString("TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A chave digitada está incorreta ou expirou..
        /// </summary>
        public static string TOKEN_INVALID_OR_EXPIRED {
            get {
                return ResourceManager.GetString("TOKEN_INVALID_OR_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível abrir o certificado digital. Verifique a senha e tenta novamente..
        /// </summary>
        public static string UNABLE_TO_OPEN_PRIVATE_KEY {
            get {
                return ResourceManager.GetString("UNABLE_TO_OPEN_PRIVATE_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha ao enviar a assinatura digital..
        /// </summary>
        public static string UNABLE_TO_SEND_DIGITAL_SIGNATURE {
            get {
                return ResourceManager.GetString("UNABLE_TO_SEND_DIGITAL_SIGNATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O acesso ao serviço do Silegis foi negado. Será necessário realizar o login novamente para acessar o sistema..
        /// </summary>
        public static string UNAUTHORIZED_HTTP {
            get {
                return ResourceManager.GetString("UNAUTHORIZED_HTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uma nova versão da aplicação está disponível. Deseja atualizar?.
        /// </summary>
        public static string UPDATE_APP {
            get {
                return ResourceManager.GetString("UPDATE_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível verificar atualizações da aplicação..
        /// </summary>
        public static string UPDATE_APP_FAIL {
            get {
                return ResourceManager.GetString("UPDATE_APP_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string USER {
            get {
                return ResourceManager.GetString("USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versão.
        /// </summary>
        public static string VERSION {
            get {
                return ResourceManager.GetString("VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao abrir o certificado. Verifique a senha digitada e tente novamente..
        /// </summary>
        public static string WRONG_PKCS12_PASSWORD {
            get {
                return ResourceManager.GetString("WRONG_PKCS12_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou senha inválidos..
        /// </summary>
        public static string WRONG_USERNAME_PASSWORD {
            get {
                return ResourceManager.GetString("WRONG_USERNAME_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
